devicesData = {
  "entry": [{
    "title": {
      "type": "text",
      "$t": "Android One"
    },
    "pxscreenw": "480",
    "sidebysidel": "1",
    "uidepth": "40",
    "screendefaultorientation": "Portrait",
    "columnsp": "4",
    "gutterl": "16",
    "devicesize": "S",
    "densitybucket": "hdpi",
    "touchsizel": "51",
    "toolbarunitl": "40",
    "inscreenw": "2.2",
    "densityoversampling": "",
    "device": "Android One",
    "toolbarunitp": "48",
    "touchsizes": "40",
    "inscreenh": "3.9",
    "platform": "Android",
    "screenppd": "45.0",
    "screenppi": "218",
    "inscreend": "4.5",
    "degscreenh": "× 18.9°",
    "viewdistance": "11.8",
    "dpscreenh": "× 569",
    "formfactor": "Handset",
    "density": "1.5",
    "sidebysidep": "1",
    "keylinel": "72",
    "columnsl": "8",
    "pxscreenh": "× 854 ",
    "dpscreenw": "320",
    "gutterp": "",
    "degscreenw": "10.7",
    "screendpa": "30.0",
    "screencanrotate": "1",
    "screendpi": "145",
    "screenratio": "16:9"
  }, {
    "title": {
      "type": "text",
      "$t": "HTC One M8"
    },
    "dpscreenw": "360",
    "pxscreenh": "× 1920 ",
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72",
    "screendpi": "147",
    "screenratio": "16:9",
    "screencanrotate": "1",
    "screendpa": "30.4",
    "degscreenw": "11.8",
    "gutterp": "",
    "inscreend": "5.0",
    "screenppi": "441",
    "degscreenh": "× 20.9°",
    "viewdistance": "11.8",
    "platform": "Android",
    "screenppd": "91.1",
    "inscreenh": "4.4",
    "toolbarunitp": "56",
    "touchsizes": "40",
    "density": "3.0",
    "formfactor": "Handset",
    "dpscreenh": "× 640",
    "touchsizel": "52",
    "device": "HTC One M8",
    "densityoversampling": "",
    "toolbarunitl": "40",
    "inscreenw": "2.5",
    "screendefaultorientation": "Portrait",
    "pxscreenw": "1080",
    "sidebysidel": "1½",
    "uidepth": "48",
    "devicesize": "M",
    "densitybucket": "xxhdpi",
    "columnsp": "4",
    "gutterl": "16"
  }, {
    "title": {
      "$t": "HTC One M9",
      "type": "text"
    },
    "devicesize": "M",
    "densitybucket": "xxhdpi",
    "columnsp": "4",
    "gutterl": "16",
    "screendefaultorientation": "Portrait",
    "pxscreenw": "1080",
    "sidebysidel": "1½",
    "uidepth": "48",
    "device": "HTC One M9",
    "densityoversampling": "",
    "inscreenw": "2.5",
    "toolbarunitl": "40",
    "touchsizel": "52",
    "formfactor": "Handset",
    "density": "3.0",
    "dpscreenh": "× 640",
    "inscreend": "5.0",
    "screenppi": "441",
    "viewdistance": "11.8",
    "degscreenh": "× 21.1°",
    "screenppd": "89.4",
    "platform": "Android",
    "inscreenh": "4.4",
    "toolbarunitp": "56",
    "touchsizes": "40",
    "screendpi": "147",
    "screenratio": "16:9",
    "screencanrotate": "1",
    "screendpa": "29.8",
    "degscreenw": "12.1",
    "gutterp": "",
    "dpscreenw": "360",
    "pxscreenh": "× 1920 ",
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72"
  }, {
    "title": {
      "$t": "LG G3",
      "type": "text"
    },
    "inscreenh": "4.8",
    "touchsizes": "49",
    "toolbarunitp": "64",
    "degscreenh": "× 22.9°",
    "viewdistance": "11.8",
    "inscreend": "5.5",
    "screenppi": "534",
    "screenppd": "110.6",
    "platform": "Android",
    "density": "3.0",
    "formfactor": "Handset",
    "dpscreenh": "× 853",
    "columnsl": "12",
    "sidebysidep": "1",
    "keylinel": "80",
    "dpscreenw": "480",
    "pxscreenh": "× 2560 ",
    "degscreenw": "13.0",
    "gutterp": "",
    "screenratio": "16:9",
    "screendpi": "178",
    "screencanrotate": "1",
    "screendpa": "36.9",
    "uidepth": "64",
    "pxscreenw": "1440",
    "sidebysidel": "2",
    "screendefaultorientation": "Portrait",
    "gutterl": "24",
    "columnsp": "8",
    "densitybucket": "xxhdpi",
    "devicesize": "L",
    "touchsizel": "63",
    "toolbarunitl": "40",
    "inscreenw": "2.7",
    "device": "LG G3",
    "densityoversampling": ""
  }, {
    "title": {
      "type": "text",
      "$t": "Moto 360"
    },
    "toolbarunitl": "40",
    "inscreenw": "1.6",
    "device": "Moto 360",
    "densityoversampling": "",
    "touchsizel": "55",
    "columnsp": "4",
    "gutterl": "16",
    "devicesize": "L",
    "densitybucket": "tvdpi",
    "pxscreenw": "320",
    "sidebysidel": "1",
    "uidepth": "24",
    "screendefaultorientation": "Landscape",
    "degscreenw": "7.6",
    "gutterp": "",
    "screendpi": "154",
    "screenratio": "32:29",
    "screendpa": "31.8",
    "screencanrotate": "",
    "columnsl": "4",
    "keylinel": "72",
    "sidebysidep": "1",
    "dpscreenw": "241",
    "pxscreenh": "× 290 ",
    "density": "1.3",
    "formfactor": "Watch",
    "dpscreenh": "× 218",
    "inscreenh": "1.4",
    "toolbarunitp": "40",
    "touchsizes": "42",
    "screenppi": "205",
    "inscreend": "1.6",
    "degscreenh": "× 6.9°",
    "viewdistance": "11.8",
    "platform": "Android",
    "screenppd": "42.3"
  }, {
    "title": {
      "$t": "Moto 360 v2 42mm",
      "type": "text"
    },
    "screendpi": "198",
    "screenratio": "65:64",
    "screendpa": "40.8",
    "screencanrotate": "",
    "degscreenw": "5.9",
    "gutterp": "",
    "dpscreenw": "241",
    "pxscreenh": "× 325 ",
    "columnsl": "4",
    "keylinel": "72",
    "sidebysidep": "1",
    "formfactor": "Watch",
    "density": "1.3",
    "dpscreenh": "× 244",
    "screenppi": "263",
    "inscreend": "1.4",
    "viewdistance": "11.8",
    "degscreenh": "× 6.0°",
    "platform": "Android",
    "screenppd": "54.3",
    "inscreenh": "1.2",
    "toolbarunitp": "40",
    "touchsizes": "54",
    "device": "Moto 360 v2 42mm",
    "densityoversampling": "",
    "toolbarunitl": "40",
    "inscreenw": "1.2",
    "touchsizel": "70",
    "devicesize": "L",
    "densitybucket": "tvdpi",
    "columnsp": "4",
    "gutterl": "16",
    "screendefaultorientation": "Portrait",
    "sidebysidel": "1",
    "pxscreenw": "320",
    "uidepth": "32"
  }, {
    "title": {
      "type": "text",
      "$t": "Moto 360 v2 46mm"
    },
    "screendpi": "175",
    "screenratio": "33:32",
    "screencanrotate": "",
    "screendpa": "36.2",
    "degscreenw": "6.7",
    "gutterp": "",
    "dpscreenw": "241",
    "pxscreenh": "× 330 ",
    "columnsl": "4",
    "keylinel": "72",
    "sidebysidep": "1",
    "formfactor": "Watch",
    "density": "1.3",
    "dpscreenh": "× 248",
    "inscreend": "1.6",
    "screenppi": "233",
    "degscreenh": "× 6.9°",
    "viewdistance": "11.8",
    "screenppd": "48.1",
    "platform": "Android",
    "inscreenh": "1.4",
    "toolbarunitp": "40",
    "touchsizes": "48",
    "device": "Moto 360 v2 46mm",
    "densityoversampling": "",
    "toolbarunitl": "40",
    "inscreenw": "1.4",
    "touchsizel": "62",
    "devicesize": "L",
    "densitybucket": "tvdpi",
    "columnsp": "4",
    "gutterl": "16",
    "screendefaultorientation": "Portrait",
    "pxscreenw": "320",
    "sidebysidel": "1",
    "uidepth": "32"
  }, {
    "title": {
      "$t": "Moto G",
      "type": "text"
    },
    "touchsizel": "58",
    "densityoversampling": "",
    "device": "Moto G",
    "inscreenw": "2.2",
    "toolbarunitl": "40",
    "screendefaultorientation": "Portrait",
    "uidepth": "48",
    "sidebysidel": "1½",
    "pxscreenw": "720",
    "densitybucket": "xhdpi",
    "devicesize": "M",
    "gutterl": "16",
    "columnsp": "4",
    "pxscreenh": "× 1280 ",
    "dpscreenw": "360",
    "sidebysidep": "1",
    "keylinel": "72",
    "columnsl": "8",
    "screendpa": "33.7",
    "screencanrotate": "1",
    "screenratio": "16:9",
    "screendpi": "163",
    "gutterp": "",
    "degscreenw": "10.7",
    "platform": "Android",
    "screenppd": "67.5",
    "viewdistance": "11.8",
    "degscreenh": "× 18.9°",
    "screenppi": "326",
    "inscreend": "4.5",
    "touchsizes": "45",
    "toolbarunitp": "56",
    "inscreenh": "3.9",
    "dpscreenh": "× 640",
    "density": "2.0",
    "formfactor": "Handset"
  }, {
    "title": {
      "type": "text",
      "$t": "Moto X"
    },
    "inscreenh": "4.1",
    "toolbarunitp": "56",
    "touchsizes": "43",
    "inscreend": "4.7",
    "screenppi": "312",
    "degscreenh": "× 19.7°",
    "viewdistance": "11.8",
    "platform": "Android",
    "screenppd": "64.6",
    "density": "2.0",
    "formfactor": "Handset",
    "dpscreenh": "× 640",
    "columnsl": "8",
    "keylinel": "72",
    "sidebysidep": "1",
    "dpscreenw": "360",
    "pxscreenh": "× 1280 ",
    "degscreenw": "11.1",
    "gutterp": "",
    "screendpi": "156",
    "screenratio": "16:9",
    "screendpa": "32.3",
    "screencanrotate": "1",
    "pxscreenw": "720",
    "sidebysidel": "1½",
    "uidepth": "48",
    "screendefaultorientation": "Portrait",
    "columnsp": "4",
    "gutterl": "16",
    "devicesize": "M",
    "densitybucket": "xhdpi",
    "touchsizel": "55",
    "inscreenw": "2.3",
    "toolbarunitl": "40",
    "device": "Moto X",
    "densityoversampling": ""
  }, {
    "title": {
      "type": "text",
      "$t": "Moto X (2nd Gen)"
    },
    "toolbarunitl": "40",
    "inscreenw": "2.5",
    "densityoversampling": "",
    "device": "Moto X (2nd Gen)",
    "touchsizel": "50",
    "columnsp": "4",
    "gutterl": "16",
    "devicesize": "M",
    "densitybucket": "xxhdpi",
    "sidebysidel": "1½",
    "pxscreenw": "1080",
    "uidepth": "48",
    "screendefaultorientation": "Portrait",
    "gutterp": "",
    "degscreenw": "12.3",
    "screencanrotate": "1",
    "screendpa": "29.2",
    "screendpi": "141",
    "screenratio": "16:9",
    "keylinel": "72",
    "sidebysidep": "1",
    "columnsl": "8",
    "pxscreenh": "× 1920 ",
    "dpscreenw": "360",
    "dpscreenh": "× 640",
    "formfactor": "Handset",
    "density": "3.0",
    "toolbarunitp": "56",
    "touchsizes": "39",
    "inscreenh": "4.5",
    "screenppd": "87.7",
    "platform": "Android",
    "screenppi": "424",
    "inscreend": "5.2",
    "degscreenh": "× 21.7°",
    "viewdistance": "11.8"
  }, {
    "title": {
      "$t": "Nexus 10",
      "type": "text"
    },
    "densityoversampling": "",
    "device": "Nexus 10",
    "inscreenw": "8.6",
    "toolbarunitl": "64",
    "touchsizel": "53",
    "devicesize": "L",
    "densitybucket": "xhdpi",
    "columnsp": "8",
    "gutterl": "24",
    "screendefaultorientation": "Landscape",
    "sidebysidel": "3+",
    "pxscreenw": "2560",
    "uidepth": "104",
    "screencanrotate": "1",
    "screendpa": "47.1",
    "screendpi": "149",
    "screenratio": "16:10",
    "gutterp": "",
    "degscreenw": "27.2",
    "pxscreenh": "× 1600 ",
    "dpscreenw": "1280",
    "keylinel": "80",
    "sidebysidep": "2",
    "columnsl": "12",
    "dpscreenh": "× 800",
    "density": "2.0",
    "formfactor": "Tablet",
    "screenppd": "94.2",
    "platform": "Android",
    "screenppi": "299",
    "inscreend": "10.1",
    "degscreenh": "× 17.2°",
    "viewdistance": "17.7",
    "toolbarunitp": "64",
    "touchsizes": "41",
    "inscreenh": "5.4"
  }, {
    "title": {
      "$t": "Nexus 6",
      "type": "text"
    },
    "platform": "Android",
    "screenppd": "102.1",
    "inscreend": "6.0",
    "screenppi": "493",
    "degscreenh": "× 24.8°",
    "viewdistance": "11.8",
    "toolbarunitp": "64",
    "touchsizes": "39",
    "inscreenh": "5.2",
    "dpscreenh": "× 731",
    "density": "3.5",
    "formfactor": "Handset",
    "pxscreenh": "× 2560 ",
    "dpscreenw": "411",
    "keylinel": "72",
    "sidebysidep": "1",
    "columnsl": "8",
    "screendpa": "29.2",
    "screencanrotate": "1",
    "screendpi": "141",
    "screenratio": "16:9",
    "gutterp": "",
    "degscreenw": "14.1",
    "screendefaultorientation": "Portrait",
    "sidebysidel": "2",
    "pxscreenw": "1440",
    "uidepth": "48",
    "devicesize": "L",
    "densitybucket": "xxxhdpi",
    "columnsp": "4",
    "gutterl": "16",
    "touchsizel": "50",
    "densityoversampling": "",
    "device": "Nexus 6",
    "toolbarunitl": "40",
    "inscreenw": "2.9"
  }, {
    "title": {
      "$t": "Nexus 5X",
      "type": "text"
    },
    "screendefaultorientation": "Portrait",
    "uidepth": "48",
    "pxscreenw": "1080",
    "sidebysidel": "2",
    "densitybucket": "xxhdpi",
    "devicesize": "L",
    "gutterl": "16",
    "columnsp": "4",
    "touchsizel": "57",
    "densityoversampling": "",
    "device": "Nexus 5X",
    "inscreenw": "2.5",
    "toolbarunitl": "40",
    "platform": "Android",
    "screenppd": "87.7",
    "viewdistance": "11.8",
    "degscreenh": "× 21.7°",
    "inscreend": "5.2",
    "screenppi": "424",
    "touchsizes": "44",
    "toolbarunitp": "64",
    "inscreenh": "4.5",
    "dpscreenh": "× 731",
    "density": "2.6",
    "formfactor": "Handset",
    "pxscreenh": "× 1920 ",
    "dpscreenw": "411",
    "keylinel": "72",
    "sidebysidep": "1",
    "columnsl": "8",
    "screencanrotate": "1",
    "screendpa": "33.4",
    "screenratio": "16:9",
    "screendpi": "161",
    "gutterp": "",
    "degscreenw": "12.3"
  }, {
    "title": {
      "$t": "Nexus 6P",
      "type": "text"
    },
    "screendpi": "147",
    "screenratio": "16:9",
    "screencanrotate": "1",
    "screendpa": "30.5",
    "degscreenw": "13.5",
    "gutterp": "",
    "dpscreenw": "411",
    "pxscreenh": "× 2560 ",
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72",
    "density": "3.5",
    "formfactor": "Handset",
    "dpscreenh": "× 731",
    "screenppi": "515",
    "inscreend": "5.7",
    "viewdistance": "11.8",
    "degscreenh": "× 23.8°",
    "screenppd": "106.7",
    "platform": "Android",
    "inscreenh": "5.0",
    "toolbarunitp": "64",
    "touchsizes": "41",
    "device": "Nexus 6P",
    "densityoversampling": "",
    "inscreenw": "2.8",
    "toolbarunitl": "40",
    "touchsizel": "52",
    "devicesize": "L",
    "densitybucket": "xxxhdpi",
    "columnsp": "4",
    "gutterl": "16",
    "screendefaultorientation": "Portrait",
    "sidebysidel": "2",
    "pxscreenw": "1440",
    "uidepth": "48"
  }, {
    "title": {
      "type": "text",
      "$t": "Google Pixel"
    },
    "dpscreenw": "411",
    "pxscreenh": "× 1920 ",
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72",
    "screendpi": "168",
    "screenratio": "16:9",
    "screendpa": "34.7",
    "screencanrotate": "1",
    "degscreenw": "11.8",
    "gutterp": "",
    "screenppi": "441",
    "inscreend": "5.0",
    "degscreenh": "× 20.9°",
    "viewdistance": "11.8",
    "platform": "Android",
    "screenppd": "91.1",
    "inscreenh": "4.4",
    "toolbarunitp": "64",
    "touchsizes": "46",
    "formfactor": "Handset",
    "density": "2.6",
    "dpscreenh": "× 731",
    "touchsizel": "59",
    "device": "Google Pixel",
    "densityoversampling": "",
    "toolbarunitl": "40",
    "inscreenw": "2.5",
    "screendefaultorientation": "Portrait",
    "sidebysidel": "2",
    "pxscreenw": "1080",
    "uidepth": "48",
    "devicesize": "L",
    "densitybucket": "xxhdpi",
    "columnsp": "4",
    "gutterl": "16"
  }, {
    "title": {
      "$t": "Google Pixel XL",
      "type": "text"
    },
    "screencanrotate": "1",
    "screendpa": "31.6",
    "screendpi": "153",
    "screenratio": "16:9",
    "gutterp": "",
    "degscreenw": "13.0",
    "pxscreenh": "× 2560 ",
    "dpscreenw": "411",
    "keylinel": "72",
    "sidebysidep": "1",
    "columnsl": "8",
    "dpscreenh": "× 731",
    "formfactor": "Handset",
    "density": "3.5",
    "platform": "Android",
    "screenppd": "110.6",
    "screenppi": "534",
    "inscreend": "5.5",
    "degscreenh": "× 22.9°",
    "viewdistance": "11.8",
    "toolbarunitp": "64",
    "touchsizes": "42",
    "inscreenh": "4.8",
    "densityoversampling": "",
    "device": "Google Pixel XL",
    "inscreenw": "2.7",
    "toolbarunitl": "40",
    "touchsizel": "54",
    "devicesize": "L",
    "densitybucket": "xxxhdpi",
    "columnsp": "4",
    "gutterl": "16",
    "screendefaultorientation": "Portrait",
    "sidebysidel": "2",
    "pxscreenw": "1440",
    "uidepth": "48"
  }, {
    "title": {
      "$t": "Nexus 7 ('12)",
      "type": "text"
    },
    "inscreend": "7.0",
    "screenppi": "216",
    "viewdistance": "17.7",
    "degscreenh": "× 19.0°",
    "screenppd": "66.9",
    "platform": "Android",
    "inscreenh": "5.9",
    "toolbarunitp": "64",
    "touchsizes": "45",
    "density": "1.3",
    "formfactor": "Tablet",
    "dpscreenh": "× 960",
    "dpscreenw": "600",
    "pxscreenh": "× 1280 ",
    "columnsl": "12",
    "keylinel": "80",
    "sidebysidep": "1",
    "screendpi": "162",
    "screenratio": "16:10",
    "screendpa": "50.2",
    "screencanrotate": "1",
    "degscreenw": "12.0",
    "gutterp": "",
    "screendefaultorientation": "Portrait",
    "pxscreenw": "800",
    "sidebysidel": "2",
    "uidepth": "72",
    "devicesize": "S",
    "densitybucket": "tvdpi",
    "columnsp": "8",
    "gutterl": "24",
    "touchsizel": "57",
    "device": "Nexus 7 ('12)",
    "densityoversampling": "",
    "toolbarunitl": "48",
    "inscreenw": "3.7"
  }, {
    "title": {
      "$t": "Nexus 7 ('13)",
      "type": "text"
    },
    "inscreenh": "6.0",
    "toolbarunitp": "64",
    "touchsizes": "44",
    "inscreend": "7.0",
    "screenppi": "323",
    "viewdistance": "17.7",
    "degscreenh": "× 19.1°",
    "platform": "Android",
    "screenppd": "100.1",
    "density": "2.0",
    "formfactor": "Tablet",
    "dpscreenh": "× 960",
    "columnsl": "12",
    "keylinel": "80",
    "sidebysidep": "1",
    "dpscreenw": "600",
    "pxscreenh": "× 1920 ",
    "degscreenw": "12.0",
    "gutterp": "",
    "screendpi": "161",
    "screenratio": "16:10",
    "screendpa": "50.1",
    "screencanrotate": "1",
    "sidebysidel": "2",
    "pxscreenw": "1200",
    "uidepth": "72",
    "screendefaultorientation": "Portrait",
    "columnsp": "8",
    "gutterl": "24",
    "devicesize": "S",
    "densitybucket": "xhdpi",
    "touchsizel": "57",
    "toolbarunitl": "48",
    "inscreenw": "3.7",
    "device": "Nexus 7 ('13)",
    "densityoversampling": ""
  }, {
    "title": {
      "$t": "Nexus 9",
      "type": "text"
    },
    "screendpa": "45.1",
    "screencanrotate": "1",
    "screendpi": "144",
    "screenratio": "4:3",
    "gutterp": "",
    "degscreenw": "22.7",
    "pxscreenh": "× 1536 ",
    "dpscreenw": "1024",
    "keylinel": "80",
    "sidebysidep": "2",
    "columnsl": "12",
    "dpscreenh": "× 768",
    "formfactor": "Tablet",
    "density": "2.0",
    "platform": "Android",
    "screenppd": "90.1",
    "screenppi": "288",
    "inscreend": "8.9",
    "viewdistance": "17.7",
    "degscreenh": "× 17.1°",
    "toolbarunitp": "64",
    "touchsizes": "40",
    "inscreenh": "5.3",
    "densityoversampling": "",
    "device": "Nexus 9",
    "toolbarunitl": "64",
    "inscreenw": "7.1",
    "touchsizel": "51",
    "devicesize": "L",
    "densitybucket": "xhdpi",
    "columnsp": "8",
    "gutterl": "24",
    "screendefaultorientation": "Landscape",
    "sidebysidel": "2½",
    "pxscreenw": "2048",
    "uidepth": "96"
  }, {
    "title": {
      "type": "text",
      "$t": "Samsung Galaxy Note 4"
    },
    "sidebysidel": "2",
    "pxscreenw": "1440",
    "uidepth": "64",
    "screendefaultorientation": "Portrait",
    "columnsp": "8",
    "gutterl": "24",
    "devicesize": "L",
    "densitybucket": "xxhdpi",
    "touchsizel": "61",
    "toolbarunitl": "40",
    "inscreenw": "2.8",
    "device": "Samsung Galaxy Note 4",
    "densityoversampling": "",
    "inscreenh": "5.0",
    "toolbarunitp": "64",
    "touchsizes": "47",
    "screenppi": "515",
    "inscreend": "5.7",
    "viewdistance": "11.8",
    "degscreenh": "× 23.8°",
    "platform": "Android",
    "screenppd": "106.7",
    "formfactor": "Handset",
    "density": "3.0",
    "dpscreenh": "× 853",
    "columnsl": "12",
    "keylinel": "80",
    "sidebysidep": "1",
    "dpscreenw": "480",
    "pxscreenh": "× 2560 ",
    "degscreenw": "13.5",
    "gutterp": "",
    "screendpi": "172",
    "screenratio": "16:9",
    "screendpa": "35.6",
    "screencanrotate": "1"
  }, {
    "title": {
      "type": "text",
      "$t": "Samsung Galaxy S5"
    },
    "devicesize": "M",
    "densitybucket": "xxhdpi",
    "columnsp": "4",
    "gutterl": "16",
    "screendefaultorientation": "Portrait",
    "pxscreenw": "1080",
    "sidebysidel": "1½",
    "uidepth": "48",
    "device": "Samsung Galaxy S5",
    "densityoversampling": "",
    "toolbarunitl": "40",
    "inscreenw": "2.9",
    "touchsizel": "51",
    "density": "3.0",
    "formfactor": "Handset",
    "dpscreenh": "× 640",
    "inscreend": "5.1",
    "screenppi": "432",
    "degscreenh": "× 26.6°",
    "viewdistance": "11.8",
    "platform": "Android",
    "screenppd": "78.5",
    "inscreenh": "5.6",
    "toolbarunitp": "56",
    "touchsizes": "40",
    "screendpi": "144",
    "screenratio": "16:9",
    "screencanrotate": "1",
    "screendpa": "26.2",
    "degscreenw": "13.8",
    "gutterp": "",
    "dpscreenw": "360",
    "pxscreenh": "× 1920 ",
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72"
  }, {
    "title": {
      "type": "text",
      "$t": "Samsung Galaxy S6"
    },
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72",
    "dpscreenw": "360",
    "pxscreenh": "× 2560 ",
    "degscreenw": "12.1",
    "gutterp": "",
    "screenratio": "16:9",
    "screendpi": "144",
    "screencanrotate": "1",
    "screendpa": "29.8",
    "inscreenh": "4.4",
    "touchsizes": "40",
    "toolbarunitp": "56",
    "degscreenh": "× 21.3°",
    "viewdistance": "11.8",
    "screenppi": "576",
    "inscreend": "5.1",
    "platform": "Android",
    "screenppd": "119.2",
    "density": "4.0",
    "formfactor": "Handset",
    "dpscreenh": "× 640",
    "touchsizel": "51",
    "inscreenw": "2.5",
    "toolbarunitl": "40",
    "device": "Samsung Galaxy S6",
    "densityoversampling": "",
    "uidepth": "48",
    "sidebysidel": "1½",
    "pxscreenw": "1440",
    "screendefaultorientation": "Portrait",
    "gutterl": "16",
    "columnsp": "4",
    "densitybucket": "xxxhdpi",
    "devicesize": "M"
  }, {
    "title": {
      "type": "text",
      "$t": "Samsung Galaxy Tab 10"
    },
    "formfactor": "Tablet",
    "density": "1.0",
    "dpscreenh": "× 1280",
    "viewdistance": "17.7",
    "degscreenh": "× 27.2°",
    "inscreend": "10.1",
    "screenppi": "149",
    "platform": "Android",
    "screenppd": "46.6",
    "inscreenh": "8.6",
    "touchsizes": "41",
    "toolbarunitp": "64",
    "screenratio": "16:10",
    "screendpi": "149",
    "screendpa": "46.6",
    "screencanrotate": "1",
    "degscreenw": "17.2",
    "gutterp": "",
    "dpscreenw": "800",
    "pxscreenh": "× 1280 ",
    "columnsl": "12",
    "sidebysidep": "2",
    "keylinel": "80",
    "densitybucket": "mdpi",
    "devicesize": "L",
    "gutterl": "24",
    "columnsp": "8",
    "screendefaultorientation": "Portrait",
    "uidepth": "104",
    "sidebysidel": "3+",
    "pxscreenw": "800",
    "device": "Samsung Galaxy Tab 10",
    "densityoversampling": "",
    "toolbarunitl": "64",
    "inscreenw": "5.4",
    "touchsizel": "53"
  }, {
    "title": {
      "type": "text",
      "$t": "iPad Mini Retina"
    },
    "toolbarunitl": "64",
    "inscreenw": "4.7",
    "device": "iPad Mini Retina",
    "densityoversampling": "",
    "touchsizel": "57",
    "columnsp": "8",
    "gutterl": "24",
    "devicesize": "L",
    "densitybucket": "xhdpi",
    "pxscreenw": "1536",
    "sidebysidel": "2½",
    "uidepth": "96",
    "screendefaultorientation": "Portrait",
    "degscreenw": "15.2",
    "gutterp": "",
    "screendpi": "162",
    "screenratio": "4:3",
    "screendpa": "50.4",
    "screencanrotate": "1",
    "columnsl": "12",
    "keylinel": "80",
    "sidebysidep": "2",
    "dpscreenw": "768",
    "pxscreenh": "× 2048 ",
    "density": "2.0",
    "formfactor": "Tablet",
    "dpscreenh": "× 1024",
    "inscreenh": "6.3",
    "toolbarunitp": "64",
    "touchsizes": "45",
    "inscreend": "7.9",
    "screenppi": "324",
    "viewdistance": "17.7",
    "degscreenh": "× 20.2°",
    "screenppd": "100.8",
    "platform": "iOS"
  }, {
    "title": {
      "type": "text",
      "$t": "iPad Retina"
    },
    "columnsp": "8",
    "gutterl": "24",
    "devicesize": "L",
    "densitybucket": "xhdpi",
    "pxscreenw": "1536",
    "sidebysidel": "2½",
    "uidepth": "96",
    "screendefaultorientation": "Portrait",
    "toolbarunitl": "64",
    "inscreenw": "5.8",
    "densityoversampling": "",
    "device": "iPad Retina",
    "touchsizel": "47",
    "dpscreenh": "× 1024",
    "formfactor": "Tablet",
    "density": "2.0",
    "toolbarunitp": "64",
    "touchsizes": "36",
    "inscreenh": "7.8",
    "platform": "iOS",
    "screenppd": "82.4",
    "inscreend": "9.7",
    "screenppi": "264",
    "viewdistance": "17.7",
    "degscreenh": "× 24.7°",
    "gutterp": "",
    "degscreenw": "18.7",
    "screencanrotate": "1",
    "screendpa": "41.2",
    "screendpi": "132",
    "screenratio": "4:3",
    "sidebysidep": "2",
    "keylinel": "80",
    "columnsl": "12",
    "pxscreenh": "× 2048 ",
    "dpscreenw": "768"
  }, {
    "title": {
      "type": "text",
      "$t": "iPad Pro"
    },
    "densityoversampling": "",
    "device": "iPad Pro",
    "toolbarunitl": "64",
    "inscreenw": "10.3",
    "touchsizel": "47",
    "densitybucket": "xhdpi",
    "devicesize": "L",
    "gutterl": "24",
    "columnsp": "12",
    "screendefaultorientation": "Landscape",
    "uidepth": "128",
    "pxscreenw": "2732",
    "sidebysidel": "3+",
    "screendpa": "42.1",
    "screencanrotate": "1",
    "screenratio": "4:3",
    "screendpi": "132",
    "gutterp": "",
    "degscreenw": "32.5",
    "pxscreenh": "× 2048 ",
    "dpscreenw": "1366",
    "sidebysidep": "2½",
    "keylinel": "80",
    "columnsl": "12",
    "dpscreenh": "× 1024",
    "density": "2.0",
    "formfactor": "Tablet",
    "platform": "iOS",
    "screenppd": "84.1",
    "viewdistance": "17.7",
    "degscreenh": "× 24.6°",
    "inscreend": "12.9",
    "screenppi": "265",
    "touchsizes": "36",
    "toolbarunitp": "64",
    "inscreenh": "7.7"
  }, {
    "title": {
      "type": "text",
      "$t": "iPhone 5"
    },
    "degscreenw": "9.5",
    "gutterp": "",
    "screendpi": "163",
    "screenratio": "16:9",
    "screencanrotate": "1",
    "screendpa": "33.7",
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72",
    "dpscreenw": "320",
    "pxscreenh": "× 1136 ",
    "formfactor": "Handset",
    "density": "2.0",
    "dpscreenh": "× 568",
    "inscreenh": "3.5",
    "toolbarunitp": "48",
    "touchsizes": "45",
    "screenppi": "326",
    "inscreend": "4.0",
    "viewdistance": "11.8",
    "degscreenh": "× 16.8°",
    "screenppd": "67.3",
    "platform": "iOS",
    "toolbarunitl": "40",
    "inscreenw": "2.0",
    "device": "iPhone 5",
    "densityoversampling": "",
    "touchsizel": "58",
    "columnsp": "4",
    "gutterl": "16",
    "devicesize": "S",
    "densitybucket": "xhdpi",
    "sidebysidel": "1",
    "pxscreenw": "640",
    "uidepth": "40",
    "screendefaultorientation": "Portrait"
  }, {
    "title": {
      "type": "text",
      "$t": "iPhone 6"
    },
    "formfactor": "Handset",
    "density": "2.0",
    "dpscreenh": "× 667",
    "inscreenh": "4.1",
    "toolbarunitp": "56",
    "touchsizes": "45",
    "inscreend": "4.7",
    "screenppi": "326",
    "degscreenh": "× 19.7°",
    "viewdistance": "11.8",
    "screenppd": "67.3",
    "platform": "iOS",
    "degscreenw": "11.1",
    "gutterp": "",
    "screendpi": "163",
    "screenratio": "16:9",
    "screencanrotate": "1",
    "screendpa": "33.7",
    "columnsl": "8",
    "sidebysidep": "1",
    "keylinel": "72",
    "dpscreenw": "375",
    "pxscreenh": "× 1334 ",
    "columnsp": "4",
    "gutterl": "16",
    "devicesize": "M",
    "densitybucket": "xhdpi",
    "sidebysidel": "1½",
    "pxscreenw": "750",
    "uidepth": "48",
    "screendefaultorientation": "Portrait",
    "toolbarunitl": "40",
    "inscreenw": "2.3",
    "device": "iPhone 6",
    "densityoversampling": "",
    "touchsizel": "58"
  }, {
    "title": {
      "type": "text",
      "$t": "iPhone 6 Plus"
    },
    "densityoversampling": "115.00%",
    "device": "iPhone 6 Plus",
    "toolbarunitl": "40",
    "inscreenw": "2.7",
    "touchsizel": "47",
    "devicesize": "L",
    "densitybucket": "xxhdpi",
    "columnsp": "4",
    "gutterl": "16",
    "screendefaultorientation": "Portrait",
    "sidebysidel": "2",
    "pxscreenw": "1080",
    "uidepth": "48",
    "screencanrotate": "1",
    "screendpa": "31.8",
    "screendpi": "134",
    "screenratio": "16:9",
    "gutterp": "",
    "degscreenw": "13.0",
    "pxscreenh": "× 1920 ",
    "dpscreenw": "414",
    "keylinel": "72",
    "sidebysidep": "1",
    "columnsl": "8",
    "dpscreenh": "× 736",
    "formfactor": "Handset",
    "density": "3.0",
    "platform": "iOS",
    "screenppd": "83.0",
    "screenppi": "401",
    "inscreend": "5.5",
    "degscreenh": "× 22.9°",
    "viewdistance": "11.8",
    "toolbarunitp": "64",
    "touchsizes": "37",
    "inscreenh": "4.8"
  }, {
    "title": {
      "$t": "Surface 3",
      "type": "text"
    },
    "screencanrotate": "1",
    "screendpa": "56.8",
    "screendpi": "136",
    "screenratio": "16:9",
    "gutterp": "",
    "degscreenw": "22.5",
    "pxscreenh": "× 1080 ",
    "dpscreenw": "1280",
    "keylinel": "80",
    "sidebysidep": "2",
    "columnsl": "12",
    "dpscreenh": "× 720",
    "density": "1.5",
    "formfactor": "Laptop",
    "platform": "Windows",
    "screenppd": "85.2",
    "inscreend": "10.8",
    "screenppi": "204",
    "viewdistance": "23.6",
    "degscreenh": "× 12.8°",
    "toolbarunitp": "64",
    "touchsizes": "37",
    "inscreenh": "5.3",
    "densityoversampling": "",
    "device": "Surface 3",
    "toolbarunitl": "64",
    "inscreenw": "9.4",
    "touchsizel": "48",
    "devicesize": "S",
    "densitybucket": "hdpi",
    "columnsp": "8",
    "gutterl": "24",
    "screendefaultorientation": "Landscape",
    "pxscreenw": "1920",
    "sidebysidel": "3+",
    "uidepth": "96"
  }, {
    "title": {
      "type": "text",
      "$t": "Surface Pro"
    },
    "touchsizes": "38",
    "toolbarunitp": "64",
    "inscreenh": "5.2",
    "screenppd": "86.8",
    "platform": "Windows",
    "viewdistance": "23.6",
    "degscreenh": "× 12.6°",
    "inscreend": "10.6",
    "screenppi": "208",
    "dpscreenh": "× 720",
    "density": "1.5",
    "formfactor": "Laptop",
    "sidebysidep": "2",
    "keylinel": "80",
    "columnsl": "12",
    "pxscreenh": "× 1080 ",
    "dpscreenw": "1280",
    "gutterp": "",
    "degscreenw": "22.1",
    "screendpa": "57.8",
    "screencanrotate": "1",
    "screenratio": "16:9",
    "screendpi": "139",
    "uidepth": "96",
    "sidebysidel": "3+",
    "pxscreenw": "1920",
    "screendefaultorientation": "Landscape",
    "gutterl": "24",
    "columnsp": "8",
    "densitybucket": "hdpi",
    "devicesize": "S",
    "touchsizel": "49",
    "toolbarunitl": "64",
    "inscreenw": "9.2",
    "densityoversampling": "",
    "device": "Surface Pro"
  }, {
    "title": {
      "$t": "Surface Pro 3",
      "type": "text"
    },
    "touchsizel": "51",
    "toolbarunitl": "64",
    "inscreenw": "10.0",
    "densityoversampling": "",
    "device": "Surface Pro 3",
    "sidebysidel": "3+",
    "pxscreenw": "2160",
    "uidepth": "120",
    "screendefaultorientation": "Landscape",
    "columnsp": "12",
    "gutterl": "24",
    "devicesize": "S",
    "densitybucket": "hdpi",
    "sidebysidep": "2",
    "keylinel": "80",
    "columnsl": "12",
    "pxscreenh": "× 1440 ",
    "dpscreenw": "1440",
    "gutterp": "",
    "degscreenw": "23.9",
    "screencanrotate": "1",
    "screendpa": "60.3",
    "screendpi": "144",
    "screenratio": "3:2",
    "toolbarunitp": "64",
    "touchsizes": "40",
    "inscreenh": "6.7",
    "platform": "Windows",
    "screenppd": "90.5",
    "screenppi": "216",
    "inscreend": "12.0",
    "degscreenh": "× 16.0°",
    "viewdistance": "23.6",
    "dpscreenh": "× 960",
    "formfactor": "Laptop",
    "density": "1.5"
  }, {
    "title": {
      "type": "text",
      "$t": "Surface Pro 4"
    },
    "toolbarunitl": "64",
    "inscreenw": "10.3",
    "device": "Surface Pro 4",
    "densityoversampling": "",
    "touchsizel": "47",
    "gutterl": "24",
    "columnsp": "12",
    "densitybucket": "xhdpi",
    "devicesize": "S",
    "uidepth": "120",
    "sidebysidel": "3+",
    "pxscreenw": "2736",
    "screendefaultorientation": "Landscape",
    "degscreenw": "24.6",
    "gutterp": "",
    "screenratio": "3:2",
    "screendpi": "133",
    "screendpa": "55.5",
    "screencanrotate": "1",
    "columnsl": "12",
    "sidebysidep": "2",
    "keylinel": "80",
    "dpscreenw": "1368",
    "pxscreenh": "× 1824 ",
    "formfactor": "Laptop",
    "density": "2.0",
    "dpscreenh": "× 912",
    "inscreenh": "6.9",
    "touchsizes": "37",
    "toolbarunitp": "64",
    "degscreenh": "× 16.6°",
    "viewdistance": "23.6",
    "screenppi": "265",
    "inscreend": "12.4",
    "platform": "Windows",
    "screenppd": "111.0"
  }, {
    "title": {
      "$t": "Surface Book",
      "type": "text"
    },
    "screencanrotate": "1",
    "screendpa": "56.1",
    "screendpi": "134",
    "screenratio": "3:2",
    "gutterp": "",
    "degscreenw": "26.8",
    "pxscreenh": "× 2000 ",
    "dpscreenw": "1500",
    "sidebysidep": "2",
    "keylinel": "80",
    "columnsl": "12",
    "dpscreenh": "× 1000",
    "density": "2.0",
    "formfactor": "Laptop",
    "platform": "Windows",
    "screenppd": "112.1",
    "inscreend": "13.5",
    "screenppi": "267",
    "degscreenh": "× 18.0°",
    "viewdistance": "23.6",
    "toolbarunitp": "64",
    "touchsizes": "37",
    "inscreenh": "7.5",
    "densityoversampling": "",
    "device": "Surface Book",
    "toolbarunitl": "64",
    "inscreenw": "11.2",
    "touchsizel": "47",
    "devicesize": "S",
    "densitybucket": "xhdpi",
    "columnsp": "12",
    "gutterl": "24",
    "screendefaultorientation": "Landscape",
    "sidebysidel": "3+",
    "pxscreenw": "3000",
    "uidepth": "128"
  }]
};
